name: Example OpenSearchTest Plan

on:
  push:
    branches:
      - main
      - feature/CCL-10788-openseach-module
  workflow_dispatch:
    inputs:
      working_directory:
        description: Terraform working directory
        required: true
        default: ./examples/cc-rubrik-poc-test
        type: string
      aws_region:
        description: AWS region
        required: true
        default: eu-west-2
        type: string
      state_bucket:
        description: S3 backend bucket name
        required: true
        default: cc-rubrik-poc-test-tfstate-opensearch
        type: string
      state_key:
        description: S3 backend state key
        required: true
        default: opensearch/example/terraform.tfstate
        type: string
      state_dynamodb_table:
        description: Optional DynamoDB state lock table name
        required: false
        default: ""
        type: string

permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  terraform-plan:
    name: Terraform Plan Example
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Init
        id: init
        uses: Home-Office-Digital/core-cloud-workflow-terraform-actions/actions/init@main
        with:
          working-directory: "${{ github.event_name == 'push' && './examples/cc-rubrik-poc-test' || inputs.working_directory }}"
          account_id: "${{ secrets.AWS_ACCOUNT_ID_RUBRIK_POC_TEST }}"
          aws-region: "${{ github.event_name == 'push' && 'eu-west-2' || inputs.aws_region }}"
          role-to-assume: "${{ secrets.AWS_ROLE_TO_ASSUME_RUBRIK_POC_TEST }}"
          state-bucket: "${{ github.event_name == 'push' && 'cc-rubrik-poc-test-tfstate-opensearch' || inputs.state_bucket }}"
          state-key: "${{ github.event_name == 'push' && 'opensearch/example/terraform.tfstate' || inputs.state_key }}"
          state-dynamodb-table: "${{ github.event_name == 'push' && '' || inputs.state_dynamodb_table }}"

      - name: Terraform Plan
        id: plan
        uses: Home-Office-Digital/core-cloud-workflow-terraform-actions/actions/plan@main
        with:
          working-directory: "${{ github.event_name == 'push' && './examples/cc-rubrik-poc-test' || inputs.working_directory }}"
          account_id: "${{ secrets.AWS_ACCOUNT_ID_RUBRIK_POC_TEST }}"
          aws-region: "${{ github.event_name == 'push' && 'eu-west-2' || inputs.aws_region }}"
          role-to-assume: "${{ secrets.AWS_ROLE_TO_ASSUME_RUBRIK_POC_TEST }}"